#!/usr/bin/env python

import sys, os, shutil, time

srcPathes = [
  "~/.vimrc",
  "~/.config/chromium/Default/Bookmarks"
]

targetsDir = "~/data/files"

delay = 3

targetsDir = os.path.expanduser(targetsDir)

while True:
  for srcPath in srcPathes:
    srcPath = os.path.expanduser(srcPath)

    targetPath = os.path.join(targetsDir, os.path.split(srcPath)[-1])

    srcMTime = os.stat(srcPath).st_mtime
    targetMTime = 0
    if os.path.exists(targetPath):
      targetMTime = os.stat(targetPath).st_mtime

    if srcMTime > targetMTime:
      shutil.copy2(srcPath, targetPath)
    elif srcMTime < targetMTime:
      shutil.copy2(targetPath, srcPath)

  time.sleep(delay)
